language: groovy
jdk:
- oraclejdk7
env:
   - TERM=dumb GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
before_script: ./gradlew testClasses
script: ./gradlew test
# The following stops Travis executing the assemble step
install: /bin/true
