language: groovy
jdk:
- oraclejdk7
env:
   - TERM=dumb GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=768m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError"
script: ./gradlew test
# The following stops Travis executing the assemble step
install: /bin/true
